variables:
  BE_IMAGE_NAME: alushkja/brewstore-backend
  BE_IMAGE_TAG: 0.0.1

stages:
  - test
  - build
  - deploy


run_backend_tests:
  stage: test
  image: maven:3-amazoncorretto-11
  script: 
    - mvn clean test -f backend/pom.xml

build_backend_artifacts:
  stage: build
  image: maven:3-amazoncorretto-11
  script:
    - mvn package -DskipTests -f backend/pom.xml
  artifacts:
    paths:
      - backend/target/quarkus-app/lib/
      - backend/target/quarkus-app/*.jar
      - backend/target/quarkus-app/app/
      - backend/target/quarkus-app/quarkus/
    expire_in: 30minute

build_backend_docker_image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PWD
    - cd backend
  script:
    - docker build -f src/main/docker/Dockerfile.jvm -t $BE_IMAGE_NAME:$BE_IMAGE_TAG .
    - docker push $BE_IMAGE_NAME:$BE_IMAGE_TAG
  after_script:
    - cd ..
  dependencies:
    - build_backend_artifacts