variables:
  BE_IMAGE_NAME: alushkja/brewstore-backend
  BE_IMAGE_TAG: 0.0.1

run_backend_tests:
  image: maven:3-amazoncorretto-11
  before_script: 
    - apt-get update && apt-get install make -y
  script: 
    - mvn test -f backend/pom.xml

build_backend_docker_image:
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PWD
    - cd backend
  script:
    - docker build -f src/main/docker/Dockerfile.jvm -t $BE_IMAGE_NAME:$BE_IMAGE_TAG .
    - docker push $BE_IMAGE_NAME:$BE_IMAGE_TAG
  after_script:
    - cd ..