name: frontend-workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
#        with:
#          node-version: '20'
#
#      - name: Check node and npm versions
#        run: npm -v && node -v
#
#      - name: Install dependencies
#        run: cd frontend && npm test

  build:
    runs-on: ubuntu-latest
#    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Check node and npm versions
        run: npm -v && node -v

      - name: Install dependencies
        run: cd frontend && npm install

      - name: Build for production
        run: cd frontend && npm run build

  build-docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Set executable permission for dockerBuildAndPush.sh
        run: chmod +x frontend/dockerBuildAndPush.sh

      - name: Build Docker image
        run: cd frontend && ./dockerBuildAndPush.sh -u ${{ secrets.DOCKER_USERNAME }} -p "${{ secrets.DOCKER_PASSWORD }}" -d -l
